//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Kategoriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Kategoriler()
        {
            this.Tbl_Urunler = new HashSet<Tbl_Urunler>();
        }
    
        public short Kategoriid { get; set; }

        [Required(ErrorMessage ="Kategori Adý boþ býrakýlamaz.")]// belirtilmemiþse, varsayýlan hata mesajý kullanýlýr.Bu varsayýlan hata mesajý genellikle "The {0} field is required." þeklindedir, burada { 0} yerine model özelliðinin adý geçer.
        public string KategoriAd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Urunler> Tbl_Urunler { get; set; }
    }
}
